export const SUBJECTS = {
  Mathematics: {
    color: "#4338CA",
    lightColor: "#EEF2FF",
    borderColor: "#818CF8",
    keywords: [
      "solve",
      "equation",
      "calculate",
      "math",
      "algebra",
      "geometry",
      "calculus",
      "derivative",
      "integral",
      "factor",
      "graph",
      "slope",
      "variable",
      "polynomial",
      "fraction",
      "percent",
      "ratio",
      "proof",
      "triangle",
      "angle",
      "circle",
      "matrix",
      "vector",
      "function",
    ],
    topics: ["Algebra", "Geometry", "Calculus", "Statistics", "Trigonometry"],
  },
  Science: {
    color: "#059669",
    lightColor: "#ECFDF5",
    borderColor: "#34D399",
    keywords: [
      "atom",
      "molecule",
      "cell",
      "biology",
      "chemistry",
      "physics",
      "reaction",
      "element",
      "compound",
      "force",
      "energy",
      "mass",
      "velocity",
      "acceleration",
      "gravity",
      "photosynthesis",
      "dna",
      "evolution",
      "ecosystem",
      "periodic",
      "bond",
      "electron",
      "nucleus",
    ],
    topics: ["Biology", "Chemistry", "Physics", "Earth Science"],
  },
  History: {
    color: "#D97706",
    lightColor: "#FFFBEB",
    borderColor: "#FCD34D",
    keywords: [
      "war",
      "revolution",
      "president",
      "century",
      "empire",
      "civilization",
      "treaty",
      "congress",
      "constitution",
      "amendment",
      "colony",
      "slavery",
      "rights",
      "movement",
      "government",
      "democracy",
      "republic",
      "ancient",
      "medieval",
      "renaissance",
      "industrial",
      "world war",
      "cold war",
    ],
    topics: ["World History", "US History", "Government", "Geography"],
  },
  English: {
    color: "#DB2777",
    lightColor: "#FDF2F8",
    borderColor: "#F9A8D4",
    keywords: [
      "essay",
      "write",
      "thesis",
      "paragraph",
      "grammar",
      "sentence",
      "poem",
      "novel",
      "character",
      "plot",
      "theme",
      "metaphor",
      "simile",
      "literary",
      "analyze",
      "argument",
      "evidence",
      "citation",
      "tone",
      "narrative",
      "dialogue",
      "punctuation",
      "vocabulary",
      "reading",
    ],
    topics: ["Writing", "Literature", "Grammar", "Reading Comprehension"],
  },
};

export const SUBJECT_NAMES = Object.keys(SUBJECTS);

export function detectSubject(text) {
  const lower = text.toLowerCase();
  const scores = {};

  for (const [subject, config] of Object.entries(SUBJECTS)) {
    scores[subject] = config.keywords.filter((keyword) =>
      lower.includes(keyword)
    ).length;
  }

  const best = Object.entries(scores).sort((a, b) => b[1] - a[1])[0];
  return best[1] > 0 ? best[0] : "Mathematics";
}
